package input

type InputIDGuestBook struct {
	ID int `uri:"id" binding:"required"`
}

type GuestBookInput struct {
	IdUndangan      string `json:"id_undangan"`
	NamaTamu        string `json:"nama_tamu"`
	StatusKehadiran string `json:"status_kehadiran"`
	Pesan           string `json:"pesan"`
}

//Generated by Micagen at 05 Juli 2022
