package input

type InputIDHadiah struct {
	ID int `uri:"id" binding:"required"`
}

type HadiahInput struct {
	IdUndangan     string `json:"id_undangan"`
	NamaBank       string `json:"nama_bank"`
	NoRekening     string `json:"no_rekening"`
	NamaPenerima   string `json:"nama_penerima"`
	AlamatPenerima string `json:"alamat_penerima"`
}

//Generated by Micagen at 05 Juli 2022
