package input

type InputIDTurutMengundang struct {
	ID int `uri:"id" binding:"required"`
}

type TurutMengundangInput struct {
	IdUndangan string `json:"id_undangan"`
	Pihak      int    `json:"pihak"`
	Nama       string `json:"nama"`
	Hubungan   string `json:"hubungan"`
}

//Generated by Micagen at 12 Juli 2022
