package input

type InputIDUndanganDetail struct {
	ID int `uri:"id" binding:"required"`
}

type UndanganDetailInput struct {
	IdUndangan   string `json:"id_undangan"`
	NamaAcara    string `json:"nama_acara"`
	TanggalAcara string `json:"tanggal_acara"`
	WaktuAcara   string `json:"waktu_acara"`
	LokasiAcara  string `json:"lokasi_acara"`
	AlamatAcara  string `json:"alamat_acara"`
}

//Generated by Micagen at 05 Juli 2022
