package input

type InputIDUser struct {
	ID int `uri:"id" binding:"required"`
}

type UserInput struct {
	NamaLengkap string `json:"nama_lengkap"`
	UserName    string `json:"user_name"`
	Password    string `json:"password"`
	Role        string `json:"role"`
}

type UserLoginInput struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

//Generated by Micagen at 05 Juli 2022
