package service

import (
	"errors"
	"undangan_online_api/entity"
	"undangan_online_api/input"
	"undangan_online_api/repository"
)

type UserService interface {
	UserServiceGetAll() ([]entity.User, error)
	UserServiceGetByID(inputID input.InputIDUser) (entity.User, error)
	UserServiceCreate(input input.UserInput) (entity.User, error)
	UserServiceUpdate(inputID input.InputIDUser, inputData input.UserInput) (entity.User, error)
	UserServiceDeleteByID(inputID input.InputIDUser) (bool, error)
	Login(input input.UserLoginInput) (entity.User, error)
}
type userService struct {
	repository repository.UserRepository
}

func NewUserService(repository repository.UserRepository) *userService {
	return &userService{repository}
}

func (s *userService) Login(input input.UserLoginInput) (entity.User, error) {
	user, err := s.repository.Login(input)

	if err != nil {
		return user, err
	}

	if user.ID == 0 {
		return user, errors.New("user tidak ditemukan, mohon periksa kembali username atau password anda")
	}

	return user, nil
}

func (s *userService) UserServiceCreate(input input.UserInput) (entity.User, error) {
	user := entity.User{}
	user.NamaLengkap = input.NamaLengkap
	user.UserName = input.UserName
	user.Password = input.Password
	user.Role = input.Role
	newUser, err := s.repository.SaveUser(user)
	if err != nil {
		return newUser, err
	}
	return newUser, nil
}
func (s *userService) UserServiceUpdate(inputID input.InputIDUser, inputData input.UserInput) (entity.User, error) {
	user, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return user, err
	}
	user.NamaLengkap = inputData.NamaLengkap
	user.UserName = inputData.UserName
	user.Password = inputData.Password
	user.Role = inputData.Role

	updatedUser, err := s.repository.UpdateUser(user)

	if err != nil {
		return updatedUser, err
	}
	return updatedUser, nil
}
func (s *userService) UserServiceGetByID(inputID input.InputIDUser) (entity.User, error) {
	user, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return user, err
	}
	return user, nil
}
func (s *userService) UserServiceGetAll() ([]entity.User, error) {
	users, err := s.repository.FindAllUser()
	if err != nil {
		return users, err
	}
	return users, nil
}
func (s *userService) UserServiceDeleteByID(inputID input.InputIDUser) (bool, error) {
	_, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return false, err
	}
	_, err = s.repository.DeleteByIDUser(inputID.ID)
	if err != nil {
		return false, err
	}
	return true, nil
}

//Generated by Micagen at 05 Juli 2022
