package repository

import (
	"undangan_online_api/entity"

	"gorm.io/gorm"
)

type TurutMengundangRepository interface {
	SaveTurutMengundang(turutmengundang entity.TurutMengundang) (entity.TurutMengundang, error)
	UpdateTurutMengundang(turutmengundang entity.TurutMengundang) (entity.TurutMengundang, error)
	FindByIDTurutMengundang(ID int) (entity.TurutMengundang, error)
	FindAllTurutMengundang() ([]entity.TurutMengundang, error)
	DeleteByIDTurutMengundang(ID int) (entity.TurutMengundang, error)
}

type turutmengundangRepository struct {
	db *gorm.DB
}

func NewTurutMengundangRepository(db *gorm.DB) *turutmengundangRepository {
	return &turutmengundangRepository{db}
}

func (r *turutmengundangRepository) SaveTurutMengundang(turutmengundang entity.TurutMengundang) (entity.TurutMengundang, error) {
	err := r.db.Create(&turutmengundang).Error
	if err != nil {
		return turutmengundang, err
	}
	return turutmengundang, nil

}
func (r *turutmengundangRepository) FindByIDTurutMengundang(ID int) (entity.TurutMengundang, error) {
	var turutmengundang entity.TurutMengundang
	err := r.db.Where("id = ? ", ID).Find(&turutmengundang).Error
	if err != nil {
		return turutmengundang, err
	}
	return turutmengundang, nil

}
func (r *turutmengundangRepository) UpdateTurutMengundang(turutmengundang entity.TurutMengundang) (entity.TurutMengundang, error) {
	err := r.db.Save(&turutmengundang).Error
	if err != nil {
		return turutmengundang, err
	}
	return turutmengundang, nil

}
func (r *turutmengundangRepository) FindAllTurutMengundang() ([]entity.TurutMengundang, error) {
	var turutmengundangs []entity.TurutMengundang
	err := r.db.Find(&turutmengundangs).Error
	if err != nil {
		return turutmengundangs, err
	}
	return turutmengundangs, nil

}
func (r *turutmengundangRepository) DeleteByIDTurutMengundang(ID int) (entity.TurutMengundang, error) {
	var turutmengundang entity.TurutMengundang
	err := r.db.Where("id = ? ", ID).Delete(&turutmengundang).Error
	if err != nil {
		return turutmengundang, err
	}
	return turutmengundang, nil

}

//Generated by Micagen at 12 Juli 2022
