package repository

import (
	"undangan_online_api/entity"

	"gorm.io/gorm"
)

type UndanganDetailRepository interface {
	SaveUndanganDetail(undangandetail entity.UndanganDetail) (entity.UndanganDetail, error)
	UpdateUndanganDetail(undangandetail entity.UndanganDetail) (entity.UndanganDetail, error)
	FindByIDUndanganDetail(ID int) (entity.UndanganDetail, error)
	FindByKodeUndanganDetail(ID string) ([]entity.UndanganDetail, error)
	FindAllUndanganDetail() ([]entity.UndanganDetail, error)
	DeleteByIDUndanganDetail(ID int) (entity.UndanganDetail, error)
}

type undangandetailRepository struct {
	db *gorm.DB
}

func NewUndanganDetailRepository(db *gorm.DB) *undangandetailRepository {
	return &undangandetailRepository{db}
}

func (r *undangandetailRepository) SaveUndanganDetail(undangandetail entity.UndanganDetail) (entity.UndanganDetail, error) {
	err := r.db.Create(&undangandetail).Error
	if err != nil {
		return undangandetail, err
	}
	return undangandetail, nil

}
func (r *undangandetailRepository) FindByIDUndanganDetail(ID int) (entity.UndanganDetail, error) {
	var undangandetail entity.UndanganDetail
	err := r.db.Where("id = ? ", ID).Find(&undangandetail).Error
	if err != nil {
		return undangandetail, err
	}
	return undangandetail, nil

}
func (r *undangandetailRepository) FindByKodeUndanganDetail(ID string) ([]entity.UndanganDetail, error) {
	var undangandetail []entity.UndanganDetail
	err := r.db.Where("id_undangan = ? ", ID).Find(&undangandetail).Error
	if err != nil {
		return undangandetail, err
	}
	return undangandetail, nil

}
func (r *undangandetailRepository) UpdateUndanganDetail(undangandetail entity.UndanganDetail) (entity.UndanganDetail, error) {
	err := r.db.Save(&undangandetail).Error
	if err != nil {
		return undangandetail, err
	}
	return undangandetail, nil

}
func (r *undangandetailRepository) FindAllUndanganDetail() ([]entity.UndanganDetail, error) {
	var undangandetails []entity.UndanganDetail
	err := r.db.Find(&undangandetails).Error
	if err != nil {
		return undangandetails, err
	}
	return undangandetails, nil

}
func (r *undangandetailRepository) DeleteByIDUndanganDetail(ID int) (entity.UndanganDetail, error) {
	var undangandetail entity.UndanganDetail
	err := r.db.Where("id = ? ", ID).Delete(&undangandetail).Error
	if err != nil {
		return undangandetail, err
	}
	return undangandetail, nil

}

//Generated by Micagen at 05 Juli 2022
