package formatter

import (
	"time"
	"undangan_online_api/entity"
)

type GuestBookFormatter struct {
	ID              int       `json:"id"`
	IdUndangan      string    `json:"id_undangan"`
	NamaTamu        string    `json:"nama_tamu"`
	StatusKehadiran string    `json:"status_kehadiran"`
	Pesan           string    `json:"pesan"`
	CreatedAt       time.Time `json:"created_at"`
}

func FormatGuestBook(guestbook entity.GuestBook) GuestBookFormatter {
	guestbookFormatter := GuestBookFormatter{}
	guestbookFormatter.ID = guestbook.ID
	guestbookFormatter.IdUndangan = guestbook.IdUndangan
	guestbookFormatter.NamaTamu = guestbook.NamaTamu
	guestbookFormatter.StatusKehadiran = guestbook.StatusKehadiran
	guestbookFormatter.Pesan = guestbook.Pesan
	guestbookFormatter.CreatedAt = guestbook.CreatedAt
	return guestbookFormatter
}
func FormatGuestBooks(guestbooks []entity.GuestBook) []GuestBookFormatter {
	guestbooksFormatter := []GuestBookFormatter{}
	for _, guestbook := range guestbooks {
		guestbookFormatter := FormatGuestBook(guestbook)
		guestbooksFormatter = append(guestbooksFormatter, guestbookFormatter)
	}
	return guestbooksFormatter
}

//Generated by Micagen at 05 Juli 2022
