package formatter

import "undangan_online_api/entity"

type LoveStoryFormatter struct {
	ID         int    `json:"id"`
	IdUndangan string `json:"id_undangan"`
	Judul      string `json:"judul"`
	Tanggal    string `json:"tanggal"`
	Tempat     string `json:"tempat"`
	Keterangan string `json:"keterangan"`
}

func FormatLoveStory(lovestory entity.LoveStory) LoveStoryFormatter {
	lovestoryFormatter := LoveStoryFormatter{}
	lovestoryFormatter.ID = lovestory.ID
	lovestoryFormatter.IdUndangan = lovestory.IdUndangan
	lovestoryFormatter.Judul = lovestory.Judul
	lovestoryFormatter.Tanggal = lovestory.Tanggal
	lovestoryFormatter.Tempat = lovestory.Tempat
	lovestoryFormatter.Keterangan = lovestory.Keterangan
	return lovestoryFormatter
}
func FormatLoveStorys(lovestorys []entity.LoveStory) []LoveStoryFormatter {
	lovestorysFormatter := []LoveStoryFormatter{}
	for _, lovestory := range lovestorys {
		lovestoryFormatter := FormatLoveStory(lovestory)
		lovestorysFormatter = append(lovestorysFormatter, lovestoryFormatter)
	}
	return lovestorysFormatter
}

//Generated by Micagen at 05 Juli 2022
