package formatter

import "undangan_online_api/entity"

type UserFormatter struct {
	ID          int    `json:"id"`
	NamaLengkap string `json:"nama_lengkap"`
	UserName    string `json:"user_name"`
	Password    string `json:"password"`
	Role        string `json:"role"`
}
type LoginUserFormatter struct {
	ID          int    `json:"id"`
	NamaLengkap string `json:"nama_lengkap"`
	UserName    string `json:"user_name"`
	Role        string `json:"role"`
	Token       string `json:"token"`
}

func FormatUser(user entity.User) UserFormatter {
	userFormatter := UserFormatter{}
	userFormatter.ID = user.ID
	userFormatter.NamaLengkap = user.NamaLengkap
	userFormatter.UserName = user.UserName
	userFormatter.Password = user.Password
	userFormatter.Role = user.Role
	return userFormatter
}
func FormatLoginUser(user entity.User, token string) LoginUserFormatter {
	userFormatter := LoginUserFormatter{}
	userFormatter.ID = user.ID
	userFormatter.NamaLengkap = user.NamaLengkap
	userFormatter.UserName = user.UserName
	userFormatter.Token = token
	userFormatter.Role = user.Role
	return userFormatter
}
func FormatUsers(users []entity.User) []UserFormatter {
	usersFormatter := []UserFormatter{}
	for _, user := range users {
		userFormatter := FormatUser(user)
		usersFormatter = append(usersFormatter, userFormatter)
	}
	return usersFormatter
}

//Generated by Micagen at 05 Juli 2022
